version: '2'

services:
  db:
    image: postgres:17.6
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    restart: always
    shm_size: '64gb'
    volumes:
      - odoo-db18-data:/var/lib/postgresql/data

  odoo18:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "11018:8069"
      - "21018:8072"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo18@2024
      - DB_NAME=postgres
    volumes:
      - odoo-web18-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
    shm_size: '16gb'

volumes:
  odoo-db18-data:
  odoo-web18-data:
